<?php

// SE-01: 26 Gulf/Islamic occasions
// Dates are for 2026. Islamic dates are approximate (subject to moon sighting).

return [

    'occasions' => [

        // ── Islamic ─────────────────────────────────────────────────────────

        [
            'key'          => 'ramadan',
            'name'         => 'رمضان المبارك',
            'subtitle'     => 'شهر القرآن والعطاء',
            'date'         => '2026-03-07',
            'end_date'     => '2026-04-05',
            'icon'         => 'moon',
            'color'        => '#0F6F5C',   // sada-500
            'countries'    => ['sa', 'ae', 'kw', 'qa', 'bh', 'om'],
            'templates'    => 24,
            'featured'     => true,
            'hashtags'     => ['#رمضان', '#رمضان_كريم', '#رمضان_مبارك', '#شهر_رمضان'],
            'is_recurring' => true,
        ],
        [
            'key'          => 'eid_fitr',
            'name'         => 'عيد الفطر المبارك',
            'subtitle'     => 'عيد الفرحة والتسامح',
            'date'         => '2026-04-06',
            'end_date'     => '2026-04-08',
            'icon'         => 'star',
            'color'        => '#C8965F',   // sand-500
            'countries'    => ['sa', 'ae', 'kw', 'qa', 'bh', 'om'],
            'templates'    => 18,
            'featured'     => true,
            'hashtags'     => ['#عيد_الفطر', '#عيد_مبارك', '#كل_عام_وانتم_بخير'],
            'is_recurring' => true,
        ],
        [
            'key'          => 'eid_adha',
            'name'         => 'عيد الأضحى المبارك',
            'subtitle'     => 'عيد التضحية والوفاء',
            'date'         => '2026-06-17',
            'end_date'     => '2026-06-20',
            'icon'         => 'moon',
            'color'        => '#C8965F',
            'countries'    => ['sa', 'ae', 'kw', 'qa', 'bh', 'om'],
            'templates'    => 14,
            'featured'     => false,
            'hashtags'     => ['#عيد_الأضحى', '#عيد_مبارك', '#أضحى_مبارك'],
            'is_recurring' => true,
        ],
        [
            'key'          => 'arafat',
            'name'         => 'يوم عرفة',
            'subtitle'     => 'يوم الدعاء والمغفرة',
            'date'         => '2026-06-16',
            'end_date'     => null,
            'icon'         => 'moon',
            'color'        => '#0A5A4B',
            'countries'    => ['sa', 'ae', 'kw', 'qa', 'bh', 'om'],
            'templates'    => 10,
            'featured'     => false,
            'hashtags'     => ['#يوم_عرفة', '#الحج'],
            'is_recurring' => true,
        ],
        [
            'key'          => 'laylat_qadr',
            'name'         => 'ليلة القدر',
            'subtitle'     => 'خير من ألف شهر',
            'date'         => '2026-04-01',
            'end_date'     => null,
            'icon'         => 'star',
            'color'        => '#7C3AED',
            'countries'    => ['sa', 'ae', 'kw', 'qa', 'bh', 'om'],
            'templates'    => 8,
            'featured'     => false,
            'hashtags'     => ['#ليلة_القدر', '#رمضان'],
            'is_recurring' => true,
        ],
        [
            'key'          => 'mawlid',
            'name'         => 'المولد النبوي الشريف',
            'subtitle'     => 'ذكرى المولد الكريم',
            'date'         => '2026-09-04',
            'end_date'     => null,
            'icon'         => 'star',
            'color'        => '#0F6F5C',
            'countries'    => ['sa', 'ae', 'kw', 'qa', 'bh', 'om'],
            'templates'    => 12,
            'featured'     => false,
            'hashtags'     => ['#المولد_النبوي', '#مولد_النبي'],
            'is_recurring' => true,
        ],
        [
            'key'          => 'hijri_new_year',
            'name'         => 'رأس السنة الهجرية',
            'subtitle'     => 'بداية عام هجري جديد',
            'date'         => '2026-07-17',
            'end_date'     => null,
            'icon'         => 'moon',
            'color'        => '#0F6F5C',
            'countries'    => ['sa', 'ae', 'kw', 'qa', 'bh', 'om'],
            'templates'    => 8,
            'featured'     => false,
            'hashtags'     => ['#رأس_السنة_الهجرية', '#عام_هجري_جديد'],
            'is_recurring' => true,
        ],

        // ── National Days ────────────────────────────────────────────────────

        [
            'key'          => 'saudi_national_day',
            'name'         => 'اليوم الوطني السعودي',
            'subtitle'     => 'ذكرى توحيد المملكة العربية السعودية · ٢٣ سبتمبر',
            'date'         => '2026-09-23',
            'end_date'     => null,
            'icon'         => 'crown',
            'color'        => '#15803D',
            'countries'    => ['sa'],
            'templates'    => 21,
            'featured'     => true,
            'hashtags'     => ['#اليوم_الوطني', '#اليوم_الوطني_السعودي', '#٢٣_سبتمبر', '#نحن_هويتنا'],
            'is_recurring' => true,
        ],
        [
            'key'          => 'saudi_founding_day',
            'name'         => 'يوم التأسيس السعودي',
            'subtitle'     => 'يوم تأسيس الدولة السعودية الأولى · ٢٢ فبراير',
            'date'         => '2026-02-22',
            'end_date'     => null,
            'icon'         => 'crown',
            'color'        => '#0A5A4B',
            'countries'    => ['sa'],
            'templates'    => 16,
            'featured'     => false,
            'hashtags'     => ['#يوم_التأسيس', '#يوم_التأسيس_السعودي'],
            'is_recurring' => true,
        ],
        [
            'key'          => 'uae_national_day',
            'name'         => 'اليوم الوطني الإماراتي',
            'subtitle'     => 'الذكرى ٥٥ لتأسيس الاتحاد · ٢ ديسمبر',
            'date'         => '2026-12-02',
            'end_date'     => null,
            'icon'         => 'crown',
            'color'        => '#EF4444',
            'countries'    => ['ae'],
            'templates'    => 19,
            'featured'     => false,
            'hashtags'     => ['#اليوم_الوطني_الإماراتي', '#يوم_الاتحاد', '#عيد_الاتحاد'],
            'is_recurring' => true,
        ],
        [
            'key'          => 'kuwait_national_day',
            'name'         => 'اليوم الوطني الكويتي',
            'subtitle'     => 'ذكرى الاستقلال الكويتي · ٢٥ فبراير',
            'date'         => '2026-02-25',
            'end_date'     => null,
            'icon'         => 'crown',
            'color'        => '#15803D',
            'countries'    => ['kw'],
            'templates'    => 14,
            'featured'     => false,
            'hashtags'     => ['#اليوم_الوطني_الكويتي', '#عيد_الاستقلال_الكويتي'],
            'is_recurring' => true,
        ],
        [
            'key'          => 'qatar_national_day',
            'name'         => 'اليوم الوطني القطري',
            'subtitle'     => 'يوم الوحدة الوطنية · ١٨ ديسمبر',
            'date'         => '2026-12-18',
            'end_date'     => null,
            'icon'         => 'crown',
            'color'        => '#9B1C1C',
            'countries'    => ['qa'],
            'templates'    => 13,
            'featured'     => false,
            'hashtags'     => ['#اليوم_الوطني_القطري', '#قطر'],
            'is_recurring' => true,
        ],
        [
            'key'          => 'bahrain_national_day',
            'name'         => 'اليوم الوطني البحريني',
            'subtitle'     => 'عيد الاستقلال البحريني · ١٦ ديسمبر',
            'date'         => '2026-12-16',
            'end_date'     => null,
            'icon'         => 'crown',
            'color'        => '#EF4444',
            'countries'    => ['bh'],
            'templates'    => 11,
            'featured'     => false,
            'hashtags'     => ['#اليوم_الوطني_البحريني', '#البحرين'],
            'is_recurring' => true,
        ],
        [
            'key'          => 'oman_national_day',
            'name'         => 'اليوم الوطني العُماني',
            'subtitle'     => 'عيد النهضة العُمانية · ١٨ نوفمبر',
            'date'         => '2026-11-18',
            'end_date'     => null,
            'icon'         => 'crown',
            'color'        => '#15803D',
            'countries'    => ['om'],
            'templates'    => 12,
            'featured'     => false,
            'hashtags'     => ['#اليوم_الوطني_العُماني', '#عُمان'],
            'is_recurring' => true,
        ],

        // ── Commercial / Social ─────────────────────────────────────────────

        [
            'key'          => 'new_year',
            'name'         => 'رأس السنة الميلادية',
            'subtitle'     => 'بداية عام ٢٠٢٧',
            'date'         => '2027-01-01',
            'end_date'     => null,
            'icon'         => 'star',
            'color'        => '#7C3AED',
            'countries'    => ['sa', 'ae', 'kw', 'qa', 'bh', 'om'],
            'templates'    => 15,
            'featured'     => false,
            'hashtags'     => ['#رأس_السنة', '#عام_جديد', '#٢٠٢٧'],
            'is_recurring' => true,
        ],
        [
            'key'          => 'valentines',
            'name'         => 'عيد الحب',
            'subtitle'     => 'يوم الوردة والمشاعر · ١٤ فبراير',
            'date'         => '2026-02-14',
            'end_date'     => null,
            'icon'         => 'heart',
            'color'        => '#EF4444',
            'countries'    => ['sa', 'ae', 'kw', 'qa', 'bh', 'om'],
            'templates'    => 13,
            'featured'     => false,
            'hashtags'     => ['#عيد_الحب', '#فالنتاين'],
            'is_recurring' => true,
        ],
        [
            'key'          => 'mothers_day',
            'name'         => 'عيد الأم',
            'subtitle'     => 'يوم تكريم الأمهات · ٢١ مارس',
            'date'         => '2026-03-21',
            'end_date'     => null,
            'icon'         => 'heart',
            'color'        => '#EC4899',
            'countries'    => ['sa', 'ae', 'kw', 'qa', 'bh', 'om'],
            'templates'    => 16,
            'featured'     => false,
            'hashtags'     => ['#عيد_الأم', '#أمي_روحي', '#يوم_الأم'],
            'is_recurring' => true,
        ],
        [
            'key'          => 'womens_day',
            'name'         => 'يوم المرأة العالمي',
            'subtitle'     => 'تمكين وإلهام · ٨ مارس',
            'date'         => '2026-03-08',
            'end_date'     => null,
            'icon'         => 'star',
            'color'        => '#7C3AED',
            'countries'    => ['sa', 'ae', 'kw', 'qa', 'bh', 'om'],
            'templates'    => 12,
            'featured'     => false,
            'hashtags'     => ['#يوم_المرأة_العالمي', '#تمكين_المرأة'],
            'is_recurring' => true,
        ],
        [
            'key'          => 'black_friday',
            'name'         => 'الجمعة البيضاء',
            'subtitle'     => 'موسم التخفيضات الكبرى',
            'date'         => '2026-11-27',
            'end_date'     => '2026-11-30',
            'icon'         => 'flash',
            'color'        => '#1E293B',
            'countries'    => ['sa', 'ae', 'kw', 'qa', 'bh', 'om'],
            'templates'    => 20,
            'featured'     => false,
            'hashtags'     => ['#الجمعة_البيضاء', '#تخفيضات', '#Black_Friday'],
            'is_recurring' => true,
        ],
        [
            'key'          => 'back_to_school',
            'name'         => 'العودة إلى المدارس',
            'subtitle'     => 'موسم بداية العام الدراسي',
            'date'         => '2026-08-25',
            'end_date'     => '2026-09-10',
            'icon'         => 'sparkle',
            'color'        => '#0284C7',
            'countries'    => ['sa', 'ae', 'kw', 'qa', 'bh', 'om'],
            'templates'    => 11,
            'featured'     => false,
            'hashtags'     => ['#العودة_للمدارس', '#بداية_الدراسة'],
            'is_recurring' => true,
        ],
        [
            'key'          => 'summer_season',
            'name'         => 'موسم الصيف',
            'subtitle'     => 'حملات الصيف والسياحة',
            'date'         => '2026-06-21',
            'end_date'     => '2026-09-22',
            'icon'         => 'flash',
            'color'        => '#F59E0B',
            'countries'    => ['sa', 'ae', 'kw', 'qa', 'bh', 'om'],
            'templates'    => 14,
            'featured'     => false,
            'hashtags'     => ['#موسم_الصيف', '#إجازة_الصيف', '#صيف'],
            'is_recurring' => true,
        ],
        [
            'key'          => 'winter_season',
            'name'         => 'موسم الشتاء',
            'subtitle'     => 'فعاليات وعروض الشتاء الخليجي',
            'date'         => '2026-12-21',
            'end_date'     => '2027-03-20',
            'icon'         => 'moon',
            'color'        => '#0284C7',
            'countries'    => ['sa', 'ae', 'kw', 'qa', 'bh', 'om'],
            'templates'    => 10,
            'featured'     => false,
            'hashtags'     => ['#موسم_الشتاء', '#شتاء'],
            'is_recurring' => true,
        ],
        [
            'key'          => 'arab_world_day',
            'name'         => 'يوم الوطن العربي',
            'subtitle'     => 'يوم التضامن العربي · ٢٢ مارس',
            'date'         => '2026-03-22',
            'end_date'     => null,
            'icon'         => 'crown',
            'color'        => '#15803D',
            'countries'    => ['sa', 'ae', 'kw', 'qa', 'bh', 'om'],
            'templates'    => 9,
            'featured'     => false,
            'hashtags'     => ['#يوم_الوطن_العربي', '#الوطن_العربي'],
            'is_recurring' => true,
        ],
        [
            'key'          => 'volunteer_day',
            'name'         => 'يوم التطوع الدولي',
            'subtitle'     => 'يوم العطاء والمساهمة · ٥ ديسمبر',
            'date'         => '2026-12-05',
            'end_date'     => null,
            'icon'         => 'heart',
            'color'        => '#0F6F5C',
            'countries'    => ['sa', 'ae', 'kw', 'qa', 'bh', 'om'],
            'templates'    => 8,
            'featured'     => false,
            'hashtags'     => ['#يوم_التطوع', '#تطوع'],
            'is_recurring' => true,
        ],
        [
            'key'          => 'bookfair_riyadh',
            'name'         => 'معرض الرياض الدولي للكتاب',
            'subtitle'     => 'موسم الثقافة والمعرفة',
            'date'         => '2026-10-01',
            'end_date'     => '2026-10-11',
            'icon'         => 'sparkle',
            'color'        => '#7C3AED',
            'countries'    => ['sa'],
            'templates'    => 7,
            'featured'     => false,
            'hashtags'     => ['#معرض_الكتاب', '#معرض_الرياض_للكتاب'],
            'is_recurring' => true,
        ],

    ],

];
